import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import Sidebar from "./Sidebar";
import SidebarRight from "./SidebarRight";
import { ArrowRight, X } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { ThemeProvider } from "next-themes";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const mockMembers = [
	{ name: "Yuki", role: "Owner" },
	{ name: "Alex", role: "Member", thinking: true },
	{ name: "Mina", role: "Member", muted: true },
	{ name: "Mina", role: "Member" },
	{ name: "Ono", role: "Designer" },
	{ name: "Kazuki", role: "Engineer" },
];

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				{/* <ThemeProvider attribute="class" defaultTheme="system" enableSystem> */}
				<div className="flex bg-white dark:bg-neutral-900">
					<Sidebar />
					<div className="flex-1 ml-56 sm:ml-64 mr-0 md:mr-56 md:sm:mr-64 min-h-screen relative w-full">
						{children}
					</div>
					<SidebarRight members={mockMembers} />
				</div>
				{/* </ThemeProvider> */}
			</body>
		</html>
	);
}
